### ISSUE TITLE
RemoteNickFormat is ignored

### ISSUE THREAD

**Issue by FunctionalHacker** [VictorNine/fbridge#4]
Hi! Thanks for this great tool, I got it working fairly easily. I will create a docker container for this when I have the time to make setting up easier.

I have one problem however: RemoteNickFormat is ignored, meaning messages sent to Facebook will just contain the message, no info on who wrote the message. Here are the relevant parts of my matterbridge.toml:

```toml
[api.myapi]
BindAddress="127.0.0.1:4242"
Buffer=1000
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

## This is the default FB gateway. All facebook measseages will be sent here
[[gateway]]
name="FBgateway"
enable=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```
